version:  "3.6"

services:
  backend:
    container_name: eval_des
    privileged: true
    build: .
    restart: always      
    ports:
      - '0.0.0.0:8080:8080'
    networks:
      local-network:
        aliases:
          - evaldes_host


networks:
  local-network:
    name: local-network
    driver: bridge